#!/usr/bin/env python3
"""Build the backward-compatible aggregate dictionary from categories."""

from pathlib import Path


ROOT = Path(__file__).parents[1]
CATEGORY_DIRECTORY = ROOT / 'github_dorks' / 'dorks'
OUTPUT = ROOT / 'github-dorks.txt'


def build(category_directory=CATEGORY_DIRECTORY, output=OUTPUT):
    sections = [
        '# Generated by scripts/build-dorks.py. Edit github_dorks/dorks/*.txt.',
        '',
    ]
    for category in sorted(category_directory.glob('*.txt')):
        sections.append(f'# Category: {category.stem}')
        sections.extend(category.read_text(encoding='utf-8').strip().splitlines())
        sections.append('')
    output.write_text('\n'.join(sections), encoding='utf-8')


if __name__ == '__main__':
    build()
